# 1. Vignette for extracting the outcome data from the RSV model and plotting

```{r}

library(patchwork) # for plotting

```


# 2. Below is an example script which plots all the incidence of each outcome per age group for each intervention programme for the cpp model

```{r}

# load dataframe with all outcomes for all interventions into dt_outcomes
load(here::here("data", "cpp_model_output", "outcomes_all.RDS"))

outcomes_plt <- df_outcomes$health_outcomes %>% pull(metric) %>% unique %>% levels # df_outcomes loaded in previous block
intervention_plt <- "PAL_VHR_S" # name of the intervention


df_outcomes$health_outcomes %>% filter(metric == "GP visits", effects == "total", inter == "PAL_VHR_S") %>% 
    group_by(seed) %>% summarise(value = sum(value))

data_plot <- df_outcomes$health_outcomes %>%
    filter(effects == "total", inter == intervention_plt)

# Example script to plot outcome absolute values
p_abs <- seq_len(length(outcomes_plt)) %>%
    map(~data_plot %>%
        filter(metric == outcomes_plt[.x]) %>%
            ggplot() +
                geom_boxplot(aes(x = age_group, y = value)) +
                facet_wrap(vars(metric)) + theme_minimal() +
                theme(axis.text.x = element_text(size = 7, angle = 90),
                    axis.title.x = element_blank(),
                    axis.title.y = element_blank())
)
wrap_plots(p_abs) + plot_annotation(title = paste0("Absolute cases for intervention: ", intervention_plt))


# If you want to plot proportion of age group then use
p_rel <- seq_len(length(outcomes_plt)) %>%
    map(~data_plot %>%
        arrange(inter, effects, metric, seed, age_group) %>%
        mutate(value_prop = value / age_pop) %>%
        filter(metric == outcomes_plt[.x]) %>%
            ggplot() +
                geom_boxplot(aes(x = age_group, y = value_prop)) +
                facet_wrap(vars(metric)) + theme_minimal() +
                theme(axis.text.x = element_text(size = 7, angle = 90),
                    axis.title.x = element_blank(),
                    axis.title.y = element_blank())
)

wrap_plots(p_rel) + plot_annotation(title = paste0("Proportional cases for intervention: ", intervention_plt))

```


# 3. Below is an example script which plots all the incidence of each outcome per age group for each intervention programme for the R model

```{r}

# Load R simualtions and name the lists
#
# Load the R simualtions of the Hodgson et al model
load(here::here("data", "inter_model_output", "all_prog_sim.RData")) # outputs
# Load all the info about the vaccination progammes, only using this for the names of the programmes
load(here::here("data", "cpp_model_output", "outcomes_all.RDS")) # df_outcomes
prog_names <- df_outcomes$health_outcomes$inter %>% levels 
# Name all the R simulations
names(outputs) <- prog_names

# Get annual incidence averaged over all seeds
annual_inci <- outputs[["NONE"]]$outcomes_week_age %>%
    group_by(outcome, time, age_group) %>%
    summarise(incidence = mean(incidence)) %>%
    group_by(outcome, age_group) %>%
    summarise(incidence = sum(incidence)) %>% as.data.frame

# Get the QALY loss values over the 10 year time horizon
## cases = QALY loss due to non-healthcare seeking (symp - (GP + hosp)) cases and healthcare seeking cases (GP + hosp cases)
## death = QALY loss due to death
## total = cases + death
qaly_th <- outputs[["NONE"]]$QALY %>%
    group_by(type, metric) %>%
    summarise(value = mean(value)) 

# Get the cost values over the 10 year time horizon
## direct = cost of treatment of all RSV cases from prospective of NHS (GP, beddays etc)
## inter = cost of implementing the intervention programme
## total = direct + inter
cost_th <- outputs[["NONE"]]$cost %>%
    group_by(type, metric) %>%
    summarise(value = mean(value)) 

# Look at vacciantion calendar
outputs[["NONE"]]$vac_cal # not very intervention of course
outputs[["MAB_ALL_S"]]$vac_cal # bit more interesting

```